
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Perfect Fake, A', '00440 Troy Avenue', 'Bagok', '81799', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Shadow of the Holy Book (Pyhän kirjan varjo)', '8312 South Court', 'Don Mueang', '55631', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Murder by Decree', '61 Bluestem Parkway', 'Xinkai', '81183', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Punk''s Dead: SLC Punk! 2', '5203 Mallard Trail', 'Caçapava', '50516', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Crucified Lovers, The (Chikamatsu monogatari)', '8 Chinook Court', 'Khayr Kōṯ', '73826', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Angel''s Leap', '61071 Eggendart Junction', 'Peredovaya', '68241', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Lady Dragon', '02765 Summerview Alley', 'Wanshi', '59889', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Passport to Pimlico', '03 Sutherland Drive', 'Wenfu', '80309', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Joysticks', '19912 Brentwood Parkway', 'Yuewan', '63210', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Julius Caesar', '67 Meadow Valley Street', 'Embu', '35007', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Faithless', '4691 New Castle Drive', 'Jiangfang', '33561', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Jaguar', '25 Forster Center', 'Sidi Yahia el Gharb', '72322', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Temptations, The', '6 Badeau Avenue', 'Gatesville', '76132', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Movie Days (Bíódagar)', '42 5th Pass', 'Sempol', '54537', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Those Who Love Me Can Take the Train (Ceux qui m''aiment prendront le train)', '200 Fair Oaks Alley', 'Rechitsy', '24644', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Four Sided Triangle', '7141 Daystar Place', 'Soutinho', '89991', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('GoldenEye', '4184 Becker Trail', 'Chalaco', '72681', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('One A.M.', '9 Anniversary Court', 'Palencia', '85604', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Flatliners', '916 Shasta Alley', 'Avon', '58371', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('When Pigs Have Wings', '42443 Red Cloud Circle', 'Sulahan', '89487', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('G.I. Joe: Operation Dragonfire', '03 Dayton Terrace', 'Magepanda', '51245', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Mother India', '47353 New Castle Point', 'Thị Trấn Hùng Quốc', '95804', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Ariel', '9973 Menomonie Point', 'Esteio', '93460', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Midnight Clear, A', '995 Dwight Court', 'Polloc', '84515', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Friends at the Margherita Cafe, The (Gli amici del bar Margherita)', '9205 Vera Place', 'Khóra', '16583', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Life of Another, The (La vie d''une autre)', '8320 Stephen Road', 'Paratinga', '19237', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Rent', '52 Annamark Way', 'Tongjiaxi', '35567', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('I Love You, I Love You (Je t''aime je t''aime)', '8998 Sutteridge Center', 'Bukui', '95501', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('The Gift of Love', '2 Florence Park', 'Tanda', '88796', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Life and Times of Allen Ginsberg, The', '8265 Declaration Circle', 'Rancanyenang', '81199', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Lucky Night', '72 Village Green Plaza', 'Malveira', '27090', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Alice', '5801 Kipling Street', 'Qingxi', '16243', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Mysteries of Lisbon (Mistérios de Lisboa)', '87 Veith Road', 'Chicago', '66546', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Anna Madelina (Ngon na ma dak lin na)', '04 Scott Avenue', 'Paracatu', '33636', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Mr. Majestyk', '64 Green Ridge Avenue', 'Qiaozi', '84407', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Walter', '56667 Hoffman Alley', 'Ryazhsk', '20964', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Kumiko, the Treasure Hunter', '82284 Shopko Road', 'Sarpang', '92939', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Johnny Got His Gun', '55 Vahlen Point', 'Duping', '45918', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Me and You and Everyone We Know', '97 Gateway Lane', 'Huangzhuang', '86732', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Oblivion', '0 Waubesa Alley', 'Cochadas', '29045', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Bonjour tristesse', '1232 American Ash Parkway', 'Ucuncha', '53233', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Garden of the Finzi-Continis, The (Giardino dei Finzi-Contini, Il)', '885 Heffernan Junction', 'Xinsheng', '57942', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Grassroots', '78 Loeprich Avenue', 'Helong', '91271', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Born on the Fourth of July', '80 Ronald Regan Street', 'Matos da Ranha', '53866', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Doctor Bull', '50 Lighthouse Bay Place', 'Starokucherganovka', '74381', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Woo', '201 Ridgeview Parkway', 'Dobřany', '52852', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Puppet Master: Axis of Evil (Puppet Master 10)', '36 Butternut Junction', 'Balfour', '86397', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('I Can''t Sleep (J''ai pas sommeil)', '6634 Thackeray Parkway', 'Liqiao', '93948', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Executioner, The (Massacre Mafia Style)', '599 Fieldstone Lane', 'Jiangkou', '37455', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('It''s a Wonderful Afterlife', '117 John Wall Center', 'Shejiang', '48394', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('My Love Has Been Burning (Waga koi wa moenu)', '78 Manufacturers Trail', 'Papeete', '54155', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Citizen Koch', '40669 Arrowood Pass', 'Mudanjiang', '43500', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Merlusse', '18 Pleasure Court', 'Vichuga', '93770', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('The Missionaries', '3 Londonderry Terrace', 'Dovhe', '99334', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Kosmos', '18 Sage Center', 'Bamenda', '17786', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Slender Thread, The', '0332 Warrior Street', 'Cataguases', '34964', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Voyage to Cythera (Taxidi sta Kythira)', '7871 Carberry Way', 'Göteborg', '70703', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Ghost, The', '01 Northland Way', 'Druzhba', '97196', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Little Help, A', '0180 School Circle', 'Krajan Timur Suger Kidul', '23271', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Love! Valour! Compassion!', '00338 Stoughton Plaza', 'Tuapukan', '43702', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('California', '7 Evergreen Drive', 'Guayabal', '34874', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Dr. Wai in the Scriptures with No Words (Mao xian wang)', '090 Hoffman Street', 'Saraburi', '13002', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Hurricane Streets', '348 Arkansas Parkway', 'Tahoua', '88733', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Mixed Blood', '29 Northview Center', 'Puncakbaru', '84919', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Moment After 2, The: The Awakening', '3 Wayridge Crossing', 'Greater Napanee', '65681', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Largo Winch (Heir Apparent: Largo Winch, The)', '5683 Village Point', 'Dallas', '68040', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Tomb, The', '524 Hanover Plaza', 'Kista', '58525', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Lola and Billy the Kid (Lola + Bilidikid)', '31302 Londonderry Court', 'Sim', '55800', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Aurora', '1213 Weeping Birch Crossing', 'Messina', '15276', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Getting Even with Dad', '23 Tennessee Terrace', 'Makedonski Brod', '44986', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Across the Bridge', '97 Hintze Terrace', 'Shuqiao', '22848', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Saving God', '263 Surrey Place', 'Hongxi', '38125', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Rumble in the Bronx (Hont faan kui)', '05712 Moulton Junction', 'Kuźnia Raciborska', '81230', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Finding North', '331 Duke Court', 'Sinjai', '32160', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Christmas Evil (a.k.a. You Better Watch Out)', '4 Thackeray Avenue', 'Xiaojia', '35451', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Forest (Rengeteg)', '11 Cherokee Park', 'Zhaobei', '17929', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Rockin'' in the Rockies', '943 Cherokee Junction', 'Zubří', '69084', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Odds Against Tomorrow', '7 Golf View Crossing', 'Mętków', '61372', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Glorious Technicolor', '06969 Harper Junction', 'Teno', '76805', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('High School Musical', '3 Mallard Terrace', 'Lewograran', '55243', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Wyatt Earp''s Revenge', '2322 Vidon Drive', 'Si Satchanalai', '70438', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('No Blade of Grass', '4581 Glacier Hill Trail', 'Marcabal', '80032', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Pacific Heights', '7 Wayridge Point', 'Huangjin', '20554', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Money Talks', '0 Mosinee Trail', 'Vysokogornyy', '37185', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Most Wanted Man, A', '30 Bonner Center', 'Lephalale', '52680', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Adventures of Arsène Lupin, The (Aventures d''Arsène Lupin, Les)', '7 Jenifer Lane', 'Měřín', '36930', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Little White Lies (Les petits mouchoirs)', '38 Golf Course Road', 'Yako', '90047', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Free Range (Ballaad maailma heakskiitmisest)', '2 Kennedy Road', 'Raduzhnyy', '86934', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Highlander: The Search for Vengeance', '67 Mesta Terrace', 'Huangling', '89404', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Bandit: Bandit''s Silver Angel (Smokey and the Bandit 7) (Bandit: Bandit and the Silver Angel)', '1 Washington Point', 'Bombu', '44309', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Sleeper', '5331 Clarendon Hill', 'Bech', '20205', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Mike Birbiglia: What I Should Have Said Was Nothing', '31429 Crest Line Street', 'Chợ Chu', '12560', 2);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Sweetwater', '8973 Mcguire Court', 'Hamada', '65936', 5);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Lost in La Mancha', '50 Dakota Point', 'Takedamachi', '38583', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('First Position', '387 Swallow Parkway', 'Zuogaiduoma', '58993', 1);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('They Died with Their Boots On', '9 Lunder Lane', 'Pedamaran', '34116', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Metalhead (Málmhaus)', '1 Schmedeman Terrace', 'Surin', '65274', 4);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Day of the Locust, The', '338 Claremont Way', 'Razvanje', '93664', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Kabluey', '5587 Surrey Center', 'Volgodonsk', '67871', 3);
insert into restaurants (restaurants_name, address_location, city, zipcode, price_range) values ('Alpha Dog', '166 Homewood Hill', 'Balucuc', '33236', 2);
